### PR TITLE
add stem chart

### PR DESCRIPTION
**Pull request by Kvaz1r**
add stem and step charts for wxmath2dplot

### CODE REVIEW

**Comment by xleclercq** [comment]
Should we make the type part of the data instead of the chart? I'm thinking that we could then display more than one data set on the same chart (e.g. one stepped and one standard).

**Comment by Kvaz1r** [comment]
Yes, I did so that to be able plot different charttypes on the same chart. I will add example.

**Comment by xleclercq** [comment]
I merged your changes but could we replace wxCHARTTYPE_STANDART with wxCHARTTYPE_LINE or something like that. It would be more descriptive.

**Comment by Kvaz1r** [comment]
@xleclercq , yes, of course. I am not not very well know English, therefore I can give incorrect names. Will be good if you change the name to something more appropriate.

**Pull request merged**
