### PR TITLE
add step chart

### LINKED ISSUE #12: Step chart
Do you plan to add support for step chart type? [Example](http://bokeh.pydata.org/en/latest/docs/gallery/step_chart.html).

### PR DESCRIPTION
**Pull request by Kvaz1r**
Resolve #12 . I guess that this variant better than create additional class for stepic chart.

### CODE REVIEW

**Comment by Kvaz1r** [comment]
@xleclercq any comment?

**Comment by xleclercq** [comment]
Sorry for the late reply. Thank you for the changes. A few comments:
1) Yes I guess there is no need to create a separate step chart. If we discover a reason to split them we can always do it then.
2) It seems you are using tabs. Can you use 4 spaces per tab instead? This will keep the code consistent.

**Comment by xleclercq** [comment]
For the enum you added. 

enum class LineType 
 +{
 + 	Standart,
 + 	Stepic
 +};

To be more like the wxWidgets style it should be:

enum wxLineType
{
    wxLINETYPE_STRAIGHTLINE,
    wxLINETYPE_STEPPEDLINE
}

**Comment by Kvaz1r** [comment]
good, updated.

**Comment by xleclercq** [comment]
Thank you!

**Pull request merged**
